### ISSUE TITLE
Support for running under async-std executor

### ISSUE THREAD

**Issue by kyrias** [durch/rust-s3#132]
**Describe the bug**
Since the crate depends on `async-std` and has generic `futures` functions it seems like the crate is meant to work when running under the `async-std` executor, rather than just `tokio`.

However, since the crate uses `reqwest` as its HTTP client, even the `futures`-based functions only function under tokio due to `reqwest` only supporting `tokio`.

**To Reproduce**
```rust
use s3::bucket::Bucket;
use s3::creds::Credentials;


#[async_std::main]
async fn main() {
    let credentials = Credentials::from_env().unwrap();

    let bucket = Bucket::new(
        "foo",
        s3::Region::Custom {
            region: "eu-central-1".to_string(),
            endpoint: "eu-central-1.linodeobjects.com".to_string(),
        },
        credentials,
    ).unwrap();


    bucket.put_object("foo", b"bar").await.unwrap();
}
```

<details>
  <summary>Backtrace</summary>

```rust
thread 'main' panicked at 'not currently running on the Tokio runtime.', /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:118:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:483:5
   1: core::panicking::panic_fmt
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/panicking.rs:85:14
   2: core::option::expect_failed
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/option.rs:1260:5
   3: core::option::Option<T>::expect
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: tokio::runtime::handle::Handle::current
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:118:9
   5: tokio::runtime::blocking::pool::spawn_blocking
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/blocking/pool.rs:65:14
   6: tokio::task::blocking::spawn_blocking
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/blocking.rs:130:9
   7: <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/dns.rs:120:24
   8: <S as hyper::client::connect::dns::sealed::Resolve>::resolve
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/dns.rs:338:13
   9: hyper::client::connect::dns::resolve::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/dns.rs:348:5
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  11: hyper::client::connect::http::HttpConnector<R>::call_async::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/http.rs:306:25
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: <hyper::client::connect::http::HttpConnector<R> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/http.rs:247:40
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  16: <hyper::client::connect::http::HttpConnecting<R> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/connect/http.rs:387:9
  17: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/either.rs:63:36
  18: <hyper_tls::client::HttpsConnector<T> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-tls-0.4.3/src/client.rs:127:23
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  21: <hyper_tls::client::HttpsConnecting<T> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-tls-0.4.3/src/client.rs:156:9
  22: reqwest::connect::Connector::connect_with_maybe_proxy::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/connect.rs:346:26
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  24: reqwest::connect::with_timeout::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/connect.rs:500:9
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  27: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/service/oneshot.rs:50:28
  28: <F as futures_core::future::TryFuture>::try_poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.7/src/future.rs:83:9
  29: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/try_future/into_future.rs:31:9
  30: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/future/map.rs:49:37
  31: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  32: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  33: <F as futures_core::future::TryFuture>::try_poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.7/src/future.rs:83:9
  34: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/try_future/into_future.rs:31:9
  35: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/future/map.rs:49:37
  36: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  37: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  38: <F as futures_core::future::TryFuture>::try_poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.7/src/future.rs:83:9
  39: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/try_future/try_flatten.rs:45:34
  40: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  41: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  42: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/either.rs:63:36
  43: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/common/lazy.rs:59:27
  44: futures_util::future::future::FutureExt::poll_unpin
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/future/mod.rs:561:9
  45: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/select.rs:92:36
  46: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/future/map.rs:49:37
  47: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  48: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/future/flatten.rs:45:36
  49: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  50: <F as futures_core::future::TryFuture>::try_poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.7/src/future.rs:83:9
  51: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/try_future/into_future.rs:31:9
  52: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/future/map.rs:49:37
  53: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  54: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  55: <F as futures_core::future::TryFuture>::try_poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.7/src/future.rs:83:9
  56: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/try_future/try_flatten.rs:45:34
  57: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  58: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  59: hyper::client::Client<C,B>::retryably_send_request::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/mod.rs:255:26
  60: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/poll_fn.rs:54:9
  61: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  62: <hyper::client::ResponseFuture as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.8/src/client/mod.rs:627:9
  63: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/async_impl/client.rs:1318:29
  64: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/async_impl/client.rs:1297:51
  65: s3::request::Request::response_future::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-s3-0.26.3/src/request.rs:486:24
  66: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  67: s3::request::Request::response_data_future::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-s3-0.26.3/src/request.rs:503:24
  68: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  69: s3::bucket::Bucket::put_object_with_content_type::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-s3-0.26.3/src/bucket.rs:772:12
  70: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  71: s3::bucket::Bucket::put_object::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-s3-0.26.3/src/bucket.rs:807:9
  72: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  73: fra::main::main::{{closure}}
             at ./src/main.rs:19:5
  74: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  75: fra::main::{{closure}}
             at ./src/main.rs:5:1
  76: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  77: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.5/src/task/builder.rs:199:17
  78: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.5/src/task/task_locals_wrapper.rs:60:13
  79: std::thread::local::LocalKey<T>::try_with
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  80: std::thread::local::LocalKey<T>::with
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  81: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.5/src/task/task_locals_wrapper.rs:55:9
  82: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.5/src/task/builder.rs:197:13
  83: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.2/src/future.rs:526:33
  84: async_executor::Executor::run::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.3.0/src/lib.rs:214:9
  85: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  86: async_executor::LocalExecutor::run::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.3.0/src/lib.rs:393:9
  87: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  88: async_io::driver::block_on
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.1.10/src/driver.rs:142:33
  89: async_global_executor::reactor::block_on::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-1.4.3/src/lib.rs:48:22
  90: async_global_executor::reactor::block_on
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-1.4.3/src/lib.rs:55:9
  91: async_global_executor::block_on::{{closure}}
             at /home/kyrias/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-1.4.3/src/lib.rs:205:36
  92: std::thread::local::LocalKey<T>::try_with
             at /home/kyrias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Expected behavior**
Uploads should function while running under `async-std`.

**Environment**
 - Rust version: nightly-2020-10-24
 - lib version: 0.26.3

**Comment by durch** [comment]
@kyrias thanks for the report, I've been eyeing this improvement for a while now, will take a closer look at implementation and report back :)

**Comment by kyrias** [comment]
Awesome, thanks!

**Comment by kennetpostigo** [comment]
@kyrias Hi, I actually just ran into the same issue, I was unsure if there was a way to plug [surf](https://github.com/http-rs/surf) and async-std into the crate through some sort of configuration. I tried a few things before realizing it was reqwest. 

@durch would we need to tell the crate to use surf & async-std when the fix lands?

**Comment by durch** [comment]
@kennetpostigo yes, it'll be feature flagged, and turning it on will swap out `reqwest` for `surf`

**Comment by durch** [comment]
#130 will land today, that in turn will make it easy to swap out backends, `async-std` should land in the next few days.

**Comment by durch** [comment]
Code is done, tests are passing. Last thing left is documentation, I'm a bit obsessive here, but I'd like to nail it. There are a lot of features now, and that could be confusing for folks

**Comment by durch** [comment]
Docs done as well, I've pushed `0.27-beta0` to crates.io in case anyone wants to test.

```toml
rust-s3 = {version = "0.27-beta0", default-features = false, features = ["with-async-std"]}
```

Turns on the `async-std` backend. In addition in case you need a sync version of the methods anywhere in the code there is the `blocking` feature which will generate a `*_blocking` method for each `async` method using `async_std::task::block_on`.

**Comment by durch** [comment]
Docs done as well, I've pushed `0.27-beta0` to crates.io in case anyone wants to test.

```toml
rust-s3 = {version = "0.27.0-beta0", default-features = false, features = ["with-async-std"]}
```

is how you can turn on the `async-std` backend. In addition in case you need a sync version of the methods anywhere in the code there is the `blocking` feature which will generate a `*_blocking` method for each `async` method using `async_std::task::block_on`.

**Comment by kyrias** [comment]
Just updated my gallery updated to `-beta1`, and it seems to be working well!
