### ISSUE TITLE
panic for https://github.com/durch/rust-s3/blob/master/s3/src/surf_request.rs(line 63)

### ISSUE THREAD

**Issue by zhuxiujia** [durch/rust-s3#241]
https://github.com/durch/rust-s3/blob/master/s3/src/surf_request.rs     (line 63)
```rust
 let response = request.send().await.unwrap();
```

**Comment by zhuxiujia** [comment]
2021-11-29 22:01:38.398548300 UTC    WARN isahc::handler - request completed with error: CouldntResolveHost: couldn't resolve host name   (C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\isahc-0.9.14\src\handler.rs:274)
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: CouldntResolveHost: couldn't resolve host name', C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-s3-0.28.0\src\surf_request.rs:68:45
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\panicking.rs:101
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\result.rs:1617
   3: enum$<core::result::Result<surf::response::Response,http_types::error::Error> >::unwrap<surf::response::Response,http_types::error::Error>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\result.rs:1299
   4: s3::surf_request::impl$1::response::generator$0
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-s3-0.28.0\src\surf_request.rs:68
   5: core::future::from_generator::impl$1::poll<s3::surf_request::impl$1::response::generator$0>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\mod.rs:80
   6: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future,assoc$<Output,enum$<core::result::Result<surf::response::Response,anyhow::Error> > > >,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\future.rs:119
   7: s3::surf_request::impl$1::response_data::generator$0
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-s3-0.28.0\src\surf_request.rs:78
   8: core::future::from_generator::impl$1::poll<s3::surf_request::impl$1::response_data::generator$0>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\mod.rs:80
   9: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future,assoc$<Output,enum$<core::result::Result<tuple$<alloc::vec::Vec<u8,alloc::alloc::Global>,u16>,anyhow::Error> > > >,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\future.rs:119
  10: s3::bucket::impl$1::create::generator$0
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-s3-0.28.0\src\bucket.rs:244
  11: core::future::from_generator::impl$1::poll<s3::bucket::impl$1::create::generator$0>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\mod.rs:80
  12: bio_service::service::oss::impl$0::test_link::generator$0
             at .\bio-service\src\service\oss.rs:217
  13: core::future::from_generator::impl$1::poll<bio_service::service::oss::impl$0::test_link::generator$0>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\mod.rs:80
  14: bio_service::controller::json_input::do_json_input::generator$0
             at .\bio-service\src\controller\json_input.rs:165
  15: core::future::from_generator::impl$1::poll<bio_service::controller::json_input::do_json_input::generator$0>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\mod.rs:80
  16: bio_service::controller::json_input::json_input::generator$0
             at .\bio-service\src\controller\json_input.rs:46
  17: core::future::from_generator::impl$1::poll<bio_service::controller::json_input::json_input::generator$0>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\mod.rs:80
  18: actix_web::handler::impl$4::poll<core::future::from_generator::GenFuture<bio_service::controller::json_input::json_input::generator$0>,actix_http::response::Response<enum$<actix_http::body::Body> > >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-3.3.2\src\handler.rs:138
  19: actix_web::handler::impl$8::poll<tuple$<actix_web::types::json::Json<bio_service::service::resp::JsonInput>,actix_web::request::HttpRequest>,actix_web::handler::Handler<core::future::from_generator::GenFuture<bio_service::controller::json_input::json_inpu
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-3.3.2\src\handler.rs:247
  20: futures_util::future::future::map::impl$2::poll<actix_web::handler::ExtractResponse<tuple$<actix_web::types::json::Json<bio_service::service::resp::JsonInput>,actix_web::request::HttpRequest>,actix_web::handler::Handler<core::future::from_generator::GenFu
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.18\src\future\future\map.rs:55
  21: futures_util::future::future::impl$15::poll<actix_web::handler::ExtractResponse<tuple$<actix_web::types::json::Json<bio_service::service::resp::JsonInput>,actix_web::request::HttpRequest>,actix_web::handler::Handler<core::future::from_generator::GenFuture
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.18\src\lib.rs:95
  22: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future,assoc$<Output,enum$<core::result::Result<actix_web::service::ServiceResponse<enum$<actix_http::body::Body> >,actix_http::error::Error> > > > >,alloc::alloc::Global> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\future.rs:119
  23: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future,assoc$<Output,enum$<core::result::Result<actix_web::service::ServiceResponse<enum$<actix_http::body::Body> >,actix_http::error::Error> > > > >,alloc::alloc::Global> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\future.rs:119
  24: futures_util::future::either::impl$4::poll<futures_util::future::ready::Ready<enum$<core::result::Result<actix_web::service::ServiceResponse<enum$<actix_http::body::Body> >,actix_http::error::Error> > >,core::pin::Pin<alloc::boxed::Box<dyn$<core::future::
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.18\src\future\either.rs:90
  25: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future,assoc$<Output,enum$<core::result::Result<actix_web::service::ServiceResponse<enum$<actix_http::body::Body> >,actix_http::error::Error> > > > >,alloc::alloc::Global> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\future.rs:119
  26: actix_http::h1::dispatcher::InnerDispatcher<tokio::net::tcp::stream::TcpStream,actix_web::app_service::AppInitService<actix_web::app_service::AppRouting,enum$<actix_http::body::Body> >,enum$<actix_http::body::Body>,actix_http::h1::expect::ExpectHandler,ac
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-2.2.1\src\h1\dispatcher.rs:400
  27: actix_http::h1::dispatcher::impl$4::poll<tokio::net::tcp::stream::TcpStream,actix_web::app_service::AppInitService<actix_web::app_service::AppRouting,enum$<actix_http::body::Body> >,enum$<actix_http::body::Body>,actix_http::h1::expect::ExpectHandler,actix
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-2.2.1\src\h1\dispatcher.rs:783
  28: enum$<actix_http::service::State<tokio::net::tcp::stream::TcpStream,actix_web::app_service::AppInitService<actix_web::app_service::AppRouting,enum$<actix_http::body::Body> >,enum$<actix_http::body::Body>,actix_http::h1::expect::ExpectHandler,actix_http::h
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-2.2.1\src\service.rs:682
  29: actix_http::service::impl$8::poll<tokio::net::tcp::stream::TcpStream,actix_web::app_service::AppInitService<actix_web::app_service::AppRouting,enum$<actix_http::body::Body> >,enum$<actix_http::body::Body>,actix_http::h1::expect::ExpectHandler,actix_http::
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-2.2.1\src\service.rs:661
  30: actix_service::and_then::impl$3::poll<actix_service::fn_service::FnService<actix_http::service::impl$3::tcp::closure$0,futures_util::future::ready::Ready<enum$<core::result::Result<tuple$<tokio::net::tcp::stream::TcpStream,enum$<actix_http::Protocol>,enum
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-service-1.0.6\src\and_then.rs:101
  31: actix_server::service::impl$1::call::generator$1<actix_service::and_then::AndThenService<actix_service::fn_service::FnService<actix_http::service::impl$3::tcp::closure$0,futures_util::future::ready::Ready<enum$<core::result::Result<tuple$<tokio::net::tcp:
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-server-1.0.4\src\service.rs:85
  32: core::future::from_generator::impl$1::poll<actix_server::service::impl$1::call::generator$1>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\mod.rs:80
  33: tokio::runtime::task::core::impl$3::poll::closure$0<core::future::from_generator::GenFuture<actix_server::service::impl$1::call::generator$1>,alloc::sync::Arc<tokio::task::local::Shared> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\core.rs:173
  34: tokio::loom::std::unsafe_cell::UnsafeCell<enum$<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture<actix_server::service::impl$1::call::generator$1> > > >::with_mut<enum$<tokio::runtime::task::core::Stage<core::future::from_generato
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\loom\std\unsafe_cell.rs:14
  35: tokio::runtime::task::core::Core<core::future::from_generator::GenFuture<actix_server::service::impl$1::call::generator$1>,alloc::sync::Arc<tokio::task::local::Shared> >::poll<core::future::from_generator::GenFuture<actix_server::service::impl$1::call::ge
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\core.rs:158
  36: tokio::runtime::task::harness::impl$1::poll::closure$0<core::future::from_generator::GenFuture<actix_server::service::impl$1::call::generator$1>,alloc::sync::Arc<tokio::task::local::Shared> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\harness.rs:107
  37: core::ops::function::FnOnce::call_once<tokio::runtime::task::harness::impl$1::poll::closure$0,tuple$<> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\ops\function.rs:227
  38: core::panic::unwind_safe::impl$23::call_once<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,tokio::runtime::task::error::JoinError>, 0, 1, Err> >, 0, 2, Ready>,tokio::runtime::task::harness::impl$1::poll::closure$0>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\panic\unwind_safe.rs:271
  39: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$1::poll::closure$0>,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,tokio::runtime::task::error::JoinError>, 0, 1, Err> >, 0, 2, R
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\panicking.rs:403
  40: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$1::poll::closure$0>,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,tokio::runtime::task::error::JoinError>, 0, 1, Err> >, 0, 2, 
  41: std::panicking::try<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,tokio::runtime::task::error::JoinError>, 0, 1, Err> >, 0, 2, Ready>,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$1::poll::closure$0> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\panicking.rs:367
  42: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$1::poll::closure$0>,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,tokio::runtime::task::error::JoinError>, 0, 1, Err> >, 0, 2, Ready
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\panic.rs:129
  43: tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture<actix_server::service::impl$1::call::generator$1>,alloc::sync::Arc<tokio::task::local::Shared> >::poll<core::future::from_generator::GenFuture<actix_server::service::impl$1::ca
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\harness.rs:89
  44: tokio::runtime::task::raw::poll<core::future::from_generator::GenFuture<actix_server::service::impl$1::call::generator$1>,alloc::sync::Arc<tokio::task::local::Shared> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\raw.rs:104
  45: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\raw.rs:66
  46: tokio::runtime::task::Notified<alloc::sync::Arc<tokio::task::local::Shared> >::run<alloc::sync::Arc<tokio::task::local::Shared> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\task\mod.rs:169
  47: tokio::task::local::impl$0::tick::closure$0
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:408
  48: tokio::coop::with_budget::closure$0<tuple$<>,tokio::task::local::impl$0::tick::closure$0>
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:127
  49: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure$0,tuple$<> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\thread\local.rs:399
  50: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure$0,tuple$<> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\thread\local.rs:375
  51: tokio::coop::with_budget
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:120
  52: tokio::coop::budget
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:96
  53: tokio::task::local::LocalSet::tick
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:408
  54: tokio::task::local::impl$5::poll::closure$0<futures_channel::oneshot::Receiver<i32> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:532
  55: tokio::macros::scoped_tls::ScopedKey<tokio::task::local::Context>::set<tokio::task::local::Context,tokio::task::local::impl$5::poll::closure$0,enum$<core::task::poll::Poll<enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> > >, 0, 1, Ready
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\macros\scoped_tls.rs:63
  56: tokio::task::local::LocalSet::with<enum$<core::task::poll::Poll<enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> > >, 0, 1, Ready>,tokio::task::local::impl$5::poll::closure$0>
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:442
  57: tokio::task::local::impl$5::poll<futures_channel::oneshot::Receiver<i32> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:518
  58: tokio::task::local::impl$0::run_until::generator$0<futures_channel::oneshot::Receiver<i32> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:392
  59: core::future::from_generator::impl$1::poll<tokio::task::local::impl$0::run_until::generator$0>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\future\mod.rs:80
  60: tokio::runtime::basic_scheduler::impl$0::block_on::closure$0::closure$0<enum$<tokio::park::either::Either<tokio::time::driver::Driver<enum$<tokio::park::either::Either<tokio::io::driver::Driver,tokio::park::thread::ParkThread> > >,enum$<tokio::park::eithe
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:131
  61: tokio::coop::with_budget::closure$0<enum$<core::task::poll::Poll<enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> > >, 0, 1, Ready>,tokio::runtime::basic_scheduler::impl$0::block_on::closure$0::closure$0>
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:127
  62: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure$0,enum$<core::task::poll::Poll<enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> > >, 0
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\thread\local.rs:399
  63: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure$0,enum$<core::task::poll::Poll<enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> > >, 0, 1,
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\thread\local.rs:375
  64: tokio::coop::with_budget
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:120
  65: tokio::coop::budget
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\coop.rs:96
  66: tokio::runtime::basic_scheduler::impl$0::block_on::closure$0<enum$<tokio::park::either::Either<tokio::time::driver::Driver<enum$<tokio::park::either::Either<tokio::io::driver::Driver,tokio::park::thread::ParkThread> > >,enum$<tokio::park::either::Either<t
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:131
  67: tokio::runtime::basic_scheduler::enter::closure$0<tokio::runtime::basic_scheduler::impl$0::block_on::closure$0,enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> >,enum$<tokio::park::either::Either<tokio::time::driver::Driver<enum$<tokio::
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:213
  68: tokio::macros::scoped_tls::ScopedKey<tokio::runtime::basic_scheduler::Context>::set<tokio::runtime::basic_scheduler::Context,tokio::runtime::basic_scheduler::enter::closure$0,enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> > >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\macros\scoped_tls.rs:63
  69: tokio::runtime::basic_scheduler::enter<tokio::runtime::basic_scheduler::impl$0::block_on::closure$0,enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> >,enum$<tokio::park::either::Either<tokio::time::driver::Driver<enum$<tokio::park::eithe
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:213
  70: tokio::runtime::basic_scheduler::BasicScheduler<enum$<tokio::park::either::Either<tokio::time::driver::Driver<enum$<tokio::park::either::Either<tokio::io::driver::Driver,tokio::park::thread::ParkThread> > >,enum$<tokio::park::either::Either<tokio::io::dri
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:123
  71: tokio::runtime::impl$0::block_on::closure$0<core::future::from_generator::GenFuture<tokio::task::local::impl$0::run_until::generator$0> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\mod.rs:444
  72: tokio::runtime::context::enter<tokio::runtime::impl$0::block_on::closure$0,enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> > >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\context.rs:72
  73: tokio::runtime::handle::Handle::enter<tokio::runtime::impl$0::block_on::closure$0,enum$<core::result::Result<i32,futures_channel::oneshot::Canceled> > >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\handle.rs:76
  74: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<tokio::task::local::impl$0::run_until::generator$0> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\mod.rs:441
  75: tokio::task::local::LocalSet::block_on<futures_channel::oneshot::Receiver<i32> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\task\local.rs:353
  76: actix_rt::runtime::Runtime::block_on<futures_channel::oneshot::Receiver<i32> >
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-1.1.1\src\runtime.rs:89
  77: actix_rt::arbiter::impl$3::new::closure$0
             at C:\Users\zhuxi\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-1.1.1\src\arbiter.rs:137
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
